apiVersion: v1
kind: Secret
metadata:
  name: db-creds
type: Opaque
stringData:
  host: {{ .Values.containers.db_host }}
  name: {{ .Values.containers.db_name }}
  user: {{ .Values.containers.db_user }}
  password: {{ .Values.containers.db_pass }}

---
apiVersion: v1
kind: Secret
metadata:
  name: git-creds
type: Opaque
stringData:
  username: {{ .Values.containers.git_username }}
  password: {{ .Values.containers.git_password }}

---
apiVersion: v1
kind: Secret
metadata:
  name: file-storage-creds
type: Opaque
stringData:
  azurestorageaccountname: {{ .Values.containers.storage_name }}
  azurestorageaccountkey: {{ .Values.containers.storage_key }}
